name: Build MythTV containers
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '05 10 * * 0' # 10:05am UTC every Sunday

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io/hal7e0

jobs:
  build-image:
    name: Build myth${{ matrix.component }} ${{ matrix.version }} container
    runs-on: ubuntu-24.04
    continue-on-error: false
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - 33
          - 34
          - 35
        component:
          - backend
          - frontend
          - web
        exclude:
          - version: 35
            component: web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine build metadata
        id: metadata
        shell: bash
        run: |
          printf 'ubuntuVersion=' >> $GITHUB_OUTPUT
          if [[ "${{ matrix.version }}" == "33" ]]; then
            printf 'jammy\n' >> $GITHUB_OUTPUT
          else
            printf 'noble\n' >> $GITHUB_OUTPUT
          fi
          printf 'date=' >> $GITHUB_OUTPUT
          date +%Y%m%d >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.component }}
          build-args: |
            MYTHTV_VERSION=${{ matrix.version }}
            UBUNTU_VERSION=${{ steps.metadata.outputs.ubuntuVersion }}
          tags: |
            ghcr.io/hal7e0/myth${{ matrix.component }}:${{ matrix.version }}
            ghcr.io/hal7e0/myth${{ matrix.component }}:${{ matrix.version }}-${{ steps.metadata.outputs.date }}
          push: ${{ github.ref == 'refs/heads/main' }}
