name: Build MythTV containers
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io/hal7e0

jobs:
  build-image:
    name: Build myth${{ matrix.component }} ${{ matrix.version }} container
    runs-on: ubuntu-24.04
    continue-on-error: false
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        version:
          - 33
          - 34
          - 35
        component:
          - backend
          - frontend
          - web
        exclude:
          - version: 35
            component: web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Get date string for tag
        id: datestr
        shell: bash
        run: |
          printf 'date=' >> $GITHUB_OUTPUT
          date +%Y%m%d >> $GITHUB_OUTPUT
          echo %GITHUB_OUTPUT

      - name: Build container image
        shell: bash
        run: |
          podman build \
            -t localhost/myth${{ matrix.component }}:${{ matrix.version }}-${{ steps.datestr.outputs.date }} \
            --build-arg=MYTHTV_VERSION=${{ matrix.version }} \
            -f ${{ matrix.component }}/myth${{ matrix.component }}.Containerfile \
            ${{ matrix.component }}/
          podman tag localhost/myth${{ matrix.component }}:${{ matrix.version }}-${{ steps.datestr.outputs.date }} \
            localhost/myth${{ matrix.component }}:${{ matrix.version }}

      - name: Fix registry case issues
        id: registry_case
        if: ${{ github.ref == 'ref/heads/main' }}
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - name: Push to ghcr.io
        uses: Wandalen/wretry.action@v3.8.0
        id: push
        if: ${{ github.ref == 'ref/heads/main' }}
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          action: redhat-actions/push-to-registry@v2
          attempt_limit: 3
          attempt_delay: 15000
          with: |
            image: myth${{ matrix.component }}
            tags: ${{ matrix.version }} ${{ matrix.version }}-${{ steps.datestr.outputs.date }}
            registry: ${{ steps.registry_case.outputs.lowercase }}
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            extra-args: --compression-format=zstd
